import Hydrate from '@/components/Hydrate'
import './globals.css'
import { Inter } from 'next/font/google'
import RegisterModal from '@/components/modal/RegisterModal'
import Providers from '@/components/Providers'
import LoginModal from '@/components/modal/LoginModal'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
      <div className='bg-bg'>
      <Hydrate>
        <RegisterModal />
        <LoginModal />
      </Hydrate>
      {children}
      </div>  
      </Providers>
      </body>
    </html>
  )
}
